# Generated by Django 5.1.3 on 2024-12-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perftitle',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
